### ISSUE TITLE
MongoDB Connection Pool

### ISSUE THREAD

**Issue by WingZer0o** [Encryption-API-Services/eas-api#257]
This happened when sending a patch of 750 requests at the server. Could be increased.

MongoDB.Driver.MongoWaitQueueFullException: The wait queue for acquiring a connection to server ac-g9js4p7-shard-00-01.erreeeq.mongodb.net:27017 is full.
   at MongoDB.Driver.Core.ConnectionPools.ExclusiveConnectionPool.AcquireConnectionHelper.AcquireWaitQueueSlot()
   at MongoDB.Driver.Core.ConnectionPools.ExclusiveConnectionPool.AcquireConnectionHelper.StartCheckingOut()
   at MongoDB.Driver.Core.ConnectionPools.ExclusiveConnectionPool.AcquireConnectionHelper.AcquireConnectionAsync(CancellationToken cancellationToken)
   at MongoDB.Driver.Core.ConnectionPools.ExclusiveConnectionPool.AcquireConnectionAsync(CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Servers.Server.GetChannelAsync(CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.RetryableWriteContext.InitializeAsync(CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.RetryableWriteContext.CreateAsync(IWriteBinding binding, Boolean retryRequested, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.BulkMixedWriteOperation.ExecuteAsync(IWriteBinding binding, CancellationToken cancellationToken)
   at MongoDB.Driver.OperationExecutor.ExecuteWriteOperationAsync[TResult](IWriteBinding binding, IWriteOperation`1 operation, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.ExecuteWriteOperationAsync[TResult](IClientSessionHandle session, IWriteOperation`1 operation, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.BulkWriteAsync(IClientSessionHandle session, IEnumerable`1 requests, BulkWriteOptions options, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.UsingImplicitSessionAsync[TResult](Func`2 funcAsync, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionBase`1.InsertOneAsync(TDocument document, InsertOneOptions options, Func`3 bulkWriteAsync)
   at DataLayer.Mongo.Repositories.HashedPasswordRepository.InsertOneHasedPassword(HashedPassword password) in C:\Code\NETCore-API\Libraries\DataLayer\Mongo\Repositories\HashedPasswordRepository.cs:line 20
   at API.ControllersLogic.PasswordControllerLogic.InsertHashedPasswordMethodRecord(HttpContext context, String methodName) in C:\Code\NETCore-API\API\ControllerLogic\PasswordControllerLogic.cs:line 288
   at API.ControllersLogic.PasswordControllerLogic.Argon2Hash(Argon2HashRequest body, HttpContext context) in C:\Code\NETCore-API\API\ControllerLogic\PasswordControllerLogic.cs:line 50

**Comment by WingZer0o** [comment]
The low budget server this is currently runs on fails at a batch of 750 requests in that short time frame. I also made only one MongoClient throughout the whole application and the logging it working. No exceptions what so ever.
